export const dataExperience = [
  { name: 'intern', value: false },
  { name: 'senior', value: false },
  { name: 'junior', value: false },
  { name: 'expert', value: false },
];

export const dataLocations = [
  { name: 'Andorra', selected: false },
  { name: 'United Arab Emirates', selected: false },
  { name: 'Afghanistan', selected: false },
  { name: 'Antigua and Barbuda', selected: false },
  { name: 'Anguilla', selected: false },
  { name: 'Albania', selected: false },
  { name: 'Armenia', selected: false },
  { name: 'Netherlands Antilles', selected: false },
  { name: 'Angola', selected: false },
  { name: 'Antarctica', selected: false },
  { name: 'Argentina', selected: false },
  { name: 'American Samoa', selected: false },
  { name: 'Austria', selected: false },
  { name: 'Australia', selected: false },
  { name: 'Aruba', selected: false },
  { name: 'Åland Islands', selected: false },
  { name: 'Azerbaijan', selected: false },
  { name: 'Bosnia and Herzegovina', selected: false },
  { name: 'Barbados', selected: false },
  { name: 'Bangladesh', selected: false },
  { name: 'Belgium', selected: false },
  { name: 'Burkina Faso', selected: false },
  { name: 'Bulgaria', selected: false },
  { name: 'Bahrain', selected: false },
  { name: 'Burundi', selected: false },
  { name: 'Benin', selected: false },
  { name: 'Saint Barthélemy', selected: false },
  { name: 'Bermuda', selected: false },
  { name: 'Brunei Darussalam', selected: false },
  { name: 'Bolivia', selected: false },
  { name: 'Bonaire, Sint Eustatius and Saba', selected: false },
  { name: 'Brazil', selected: false },
  { name: 'Bahamas', selected: false },
  { name: 'Bhutan', selected: false },
  { name: 'Bouvet Island', selected: false },
  { name: 'Botswana', selected: false },
  { name: 'Belarus', selected: false },
  { name: 'Belize', selected: false },
  { name: 'Canada', selected: false },
  { name: 'Cocos(Keeling) Islands', selected: false },
  { name: 'Congo, The Democratic Republic Of The', selected: false },
  { name: 'Central African Republic', selected: false },
  { name: 'Congo', selected: false },
  { name: 'Switzerland', selected: false },
  { name: 'Côte D\'Ivoire', selected: false },
  { name: 'Cook Islands', selected: false },
  { name: 'Chile', selected: false },
  { name: 'Cameroon', selected: false },
  { name: 'China', selected: false },
  { name: 'Colombia', selected: false },
  { name: 'Costa Rica', selected: false },
  { name: 'Cuba', selected: false },
  { name: 'Cape Verde', selected: false },
  { name: 'Curaçao', selected: false },
  { name: 'Christmas Island', selected: false },
  { name: 'Cyprus', selected: false },
  { name: 'Czech Republic', selected: false },
  { name: 'Germany', selected: false },
  { name: 'Djibouti', selected: false },
  { name: 'Denmark', selected: false },
  { name: 'Dominica', selected: false },
  { name: 'Dominican Republic', selected: false },
  { name: 'Algeria', selected: false },
  { name: 'Ecuador', selected: false },
  { name: 'Estonia', selected: false },
  { name: 'Egypt', selected: false },
  { name: 'Western Sahara', selected: false },
  { name: 'Eritrea', selected: false },
  { name: 'Spain', selected: false },
  { name: 'Ethiopia', selected: false },
  { name: 'Finland', selected: false },
  { name: 'Fiji', selected: false },
  { name: 'Falkland Islands(Malvinas)', selected: false },
  { name: 'Micronesia, Federated States Of', selected: false },
  { name: 'Faroe Islands', selected: false },
  { name: 'France', selected: false },
  { name: 'Gabon', selected: false },
  { name: 'United Kingdom', selected: false },
  { name: 'Grenada', selected: false },
  { name: 'Georgia', selected: false },
  { name: 'French Guiana', selected: false },
  { name: 'Guernsey', selected: false },
  { name: 'Ghana', selected: false },
  { name: 'Gibraltar', selected: false },
  { name: 'Greenland', selected: false },
  { name: 'Gambia', selected: false },
  { name: 'Guinea', selected: false },
  { name: 'Guadeloupe', selected: false },
  { name: 'Equatorial Guinea', selected: false },
  { name: 'Greece', selected: false },
  { name: 'South Georgia and the South Sandwich Islands', selected: false },
  { name: 'Guatemala', selected: false },
  { name: 'Guam', selected: false },
  { name: 'Guinea - Bissau', selected: false },
  { name: 'Guyana', selected: false },
  { name: 'Hong Kong', selected: false },
  { name: 'Heard and McDonald Islands', selected: false },
  { name: 'Honduras', selected: false },
  { name: 'Croatia', selected: false },
  { name: 'Haiti', selected: false },
  { name: 'Hungary', selected: false },
  { name: 'Indonesia', selected: false },
  { name: 'Ireland', selected: false },
  { name: 'Israel', selected: false },
  { name: 'Isle of Man', selected: false },
  { name: 'India', selected: false },
  { name: 'British Indian Ocean Territory', selected: false },
  { name: 'Iraq', selected: false },
  { name: 'Iran, Islamic Republic Of', selected: false },
  { name: 'Iceland', selected: false },
  { name: 'Italy', selected: false },
  { name: 'Jersey', selected: false },
  { name: 'Jamaica', selected: false },
  { name: 'Jordan', selected: false },
  { name: 'Japan', selected: false },
  { name: 'Kenya', selected: false },
  { name: 'Kyrgyzstan', selected: false },
  { name: 'Cambodia', selected: false },
  { name: 'Kiribati', selected: false },
  { name: 'Comoros', selected: false },
  { name: 'Saint Kitts And Nevis', selected: false },
  { name: 'Korea, Democratic People\'s Republic Of', selected: false },
  { name: 'Korea, Republic of', selected: false },
  { name: 'Kuwait', selected: false },
  { name: 'Cayman Islands', selected: false },
  { name: 'Kazakhstan', selected: false },
  { name: 'Lao People\'s Democratic Republic', selected: false },
  { name: 'Lebanon', selected: false },
  { name: 'Saint Lucia', selected: false },
  { name: 'Liechtenstein', selected: false },
  { name: 'Sri Lanka', selected: false },
  { name: 'Liberia', selected: false },
  { name: 'Lesotho', selected: false },
  { name: 'Lithuania', selected: false },
  { name: 'Luxembourg', selected: false },
  { name: 'Latvia', selected: false },
  { name: 'Libya', selected: false },
  { name: 'Morocco', selected: false },
  { name: 'Monaco', selected: false },
  { name: 'Moldova, Republic of', selected: false },
  { name: 'Montenegro', selected: false },
  { name: 'Saint Martin', selected: false },
  { name: 'Madagascar', selected: false },
  { name: 'Marshall Islands', selected: false },
  { name: 'Macedonia, the Former Yugoslav Republic Of', selected: false },
  { name: 'Mali', selected: false },
  { name: 'Myanmar', selected: false },
  { name: 'Mongolia', selected: false },
  { name: 'Macao', selected: false },
  { name: 'Northern Mariana Islands', selected: false },
  { name: 'Martinique', selected: false },
  { name: 'Mauritania', selected: false },
  { name: 'Montserrat', selected: false },
  { name: 'Malta', selected: false },
  { name: 'Mauritius', selected: false },
  { name: 'Maldives', selected: false },
  { name: 'Malawi', selected: false },
  { name: 'Mexico', selected: false },
  { name: 'Malaysia', selected: false },
  { name: 'Mozambique', selected: false },
  { name: 'Namibia', selected: false },
  { name: 'New Caledonia', selected: false },
  { name: 'Niger', selected: false },
  { name: 'Norfolk Island', selected: false },
  { name: 'Nigeria', selected: false },
  { name: 'Nicaragua', selected: false },
  { name: 'Netherlands', selected: false },
  { name: 'Norway', selected: false },
  { name: 'Nepal', selected: false },
  { name: 'Nauru', selected: false },
  { name: 'Niue', selected: false },
  { name: 'New Zealand', selected: false },
  { name: 'Oman', selected: false },
  { name: 'Panama', selected: false },
  { name: 'Peru', selected: false },
  { name: 'French Polynesia', selected: false },
  { name: 'Papua New Guinea', selected: false },
  { name: 'Philippines', selected: false },
  { name: 'Pakistan', selected: false },
  { name: 'Poland', selected: false },
  { name: 'Saint Pierre And Miquelon', selected: false },
  { name: 'Pitcairn', selected: false },
  { name: 'Puerto Rico', selected: false },
  { name: 'Palestine, State of', selected: false },
  { name: 'Portugal', selected: false },
  { name: 'Palau', selected: false },
  { name: 'Paraguay', selected: false },
  { name: 'Qatar', selected: false },
  { name: 'Réunion', selected: false },
  { name: 'Romania', selected: false },
  { name: 'Serbia', selected: false },
  { name: 'Russian Federation', selected: false },
  { name: 'Rwanda', selected: false },
  { name: 'Saudi Arabia', selected: false },
  { name: 'Solomon Islands', selected: false },
  { name: 'Seychelles', selected: false },
  { name: 'Sudan', selected: false },
  { name: 'Sweden', selected: false },
  { name: 'Singapore', selected: false },
  { name: 'Saint Helena', selected: false },
  { name: 'Slovenia', selected: false },
  { name: 'Svalbard And Jan Mayen', selected: false },
  { name: 'Slovakia', selected: false },
  { name: 'Sierra Leone', selected: false },
  { name: 'San Marino', selected: false },
  { name: 'Senegal', selected: false },
  { name: 'Somalia', selected: false },
  { name: 'Suriname', selected: false },
  { name: 'South Sudan', selected: false },
  { name: 'Sao Tome and Principe', selected: false },
  { name: 'El Salvador', selected: false },
  { name: 'Sint Maarten', selected: false },
  { name: 'Syrian Arab Republic', selected: false },
  { name: 'Swaziland', selected: false },
  { name: 'Turks and Caicos Islands', selected: false },
  { name: 'Chad', selected: false },
  { name: 'French Southern Territories', selected: false },
  { name: 'Togo', selected: false },
  { name: 'Thailand', selected: false },
  { name: 'Tajikistan', selected: false },
  { name: 'Tokelau', selected: false },
  { name: 'Timor-Leste', selected: false },
  { name: 'Turkmenistan', selected: false },
  { name: 'Tunisia', selected: false },
  { name: 'Tonga', selected: false },
  { name: 'Turkey', selected: false },
  { name: 'Trinidad and Tobago', selected: false },
  { name: 'Tuvalu', selected: false },
  { name: 'Taiwan, Republic Of China', selected: false },
  { name: 'Tanzania, United Republic of', selected: false },
  { name: 'Ukraine', selected: false },
  { name: 'Uganda', selected: false },
  { name: 'United States Minor Outlying Islands', selected: false },
  { name: ' United States', selected: false },
  { name: 'Uruguay', selected: false },
  { name: 'Uzbekistan', selected: false },
  { name: 'Holy See(Vatican City State)', selected: false },
  { name: 'Saint Vincent And The Grenadines', selected: false },
  { name: 'Venezuela, Bolivarian Republic of', selected: false },
  { name: 'Virgin Islands, British', selected: false },
  { name: 'Virgin Islands, U.S.', selected: false },
  { name: 'Vietnam', selected: false },
  { name: 'Vanuatu', selected: false },
  { name: 'Wallis and Futuna', selected: false },
  { name: 'Samoa', selected: false },
  { name: 'Yemen', selected: false },
  { name: 'Mayotte', selected: false },
  { name: 'South Africa', selected: false },
  { name: 'Zambia', selected: false },
  { name: 'Zimbabwe', selected: false },
];

export const dataLanguages = [
  { name: 'Afrikanns', selected: false },
  { name: 'Albanian', selected: false },
  { name: 'Arabic', selected: false },
  { name: 'Armenian', selected: false },
  { name: 'Basque', selected: false },
  { name: 'Bengali', selected: false },
  { name: 'Bulgarian', selected: false },
  { name: 'Catalan', selected: false },
  { name: 'Cambodian', selected: false },
  { name: 'Chinese(Mandarin)', selected: false },
  { name: 'Croation', selected: false },
  { name: 'Czech', selected: false },
  { name: 'Danish', selected: false },
  { name: 'Dutch', selected: false },
  { name: 'English', selected: false },
  { name: 'Estonian', selected: false },
  { name: 'Fiji', selected: false },
  { name: 'Finnish', selected: false },
  { name: 'French', selected: false },
  { name: 'Georgian', selected: false },
  { name: 'German', selected: false },
  { name: 'Greek', selected: false },
  { name: 'Gujarati', selected: false },
  { name: 'Hebrew', selected: false },
  { name: 'Hindi', selected: false },
  { name: 'Hungarian', selected: false },
  { name: 'Icelandic', selected: false },
  { name: 'Indonesian', selected: false },
  { name: 'Irish', selected: false },
  { name: 'Italian', selected: false },
  { name: 'Japanese', selected: false },
  { name: 'Javanese', selected: false },
  { name: 'Korean', selected: false },
  { name: 'Latin', selected: false },
  { name: 'Latvian', selected: false },
  { name: 'Lithuanian', selected: false },
  { name: 'Macedonian', selected: false },
  { name: 'Malay', selected: false },
  { name: 'Malayalam', selected: false },
  { name: 'Maltese', selected: false },
  { name: 'Maori', selected: false },
  { name: 'Marathi', selected: false },
  { name: 'Mongolian', selected: false },
  { name: 'Nepali', selected: false },
  { name: 'Norwegian', selected: false },
  { name: 'Persian', selected: false },
  { name: 'Polish', selected: false },
  { name: 'Portuguese', selected: false },
  { name: 'Punjabi', selected: false },
  { name: 'Quechua', selected: false },
  { name: 'Romanian', selected: false },
  { name: 'Russian', selected: false },
  { name: 'Samoan', selected: false },
  { name: 'Serbian', selected: false },
  { name: 'Slovak', selected: false },
  { name: 'Slovenian', selected: false },
  { name: 'Spanish', selected: false },
  { name: 'Swahili', selected: false },
  { name: 'Swedish', selected: false },
  { name: 'Tamil', selected: false },
  { name: 'Tatar', selected: false },
  { name: 'Telugu', selected: false },
  { name: 'Thai', selected: false },
  { name: 'Tibetan', selected: false },
  { name: 'Tonga', selected: false },
  { name: 'Turkish', selected: false },
  { name: 'Ukranian', selected: false },
  { name: 'Urdu', selected: false },
  { name: 'Uzbek', selected: false },
  { name: 'Vietnamese', selected: false },
  { name: 'Welsh', selected: false },
  { name: 'Xhosa', selected: false },
];

export const dataAvailability = [
  { name: 'per_week_up_to_20', text: '< 20h', selected: false },
  { name: 'per_week_30', text: '< 30h', selected: false },
  { name: 'per_week_more_than_30', text: '> 30h', selected: false },
  { name: 'per_week_full_time', text: 'Full Time', selected: false },
];

export const dataPlaceOfWork = [
  { name: 'online', text: 'On-Line', selected: false },
  { name: 'onsite', text: 'On-Site', selected: false },
];